name: Update README with AutoGen Output

on:
  push:
    branches: [main]  # Run on pushes to main
  workflow_dispatch:   # Allow manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # or your version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run AutoGen script
        run: |
          python src/autogen_project.py

      - name: Commit and push README changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update README with AutoGen output" || echo "No changes to commit"
          git push origin main
